### PR TITLE
Iterated hashing with CLNH

### PR DESCRIPTION
**Pull request by jbapple**
This speed is between CLHASH and multilinear half-multiplication on my machine.

### CODE REVIEW

**Comment by lemire** [comment]
Interesting. Is the resulting function universal?

**Comment by jbapple** [comment]
It is approximately (L/2)/2^64 almost big-endian universal, where L is the length of the longest input in 64-bit words. As you know, the last hash function applied (`bie` in this case) can't decrease the numerator, but can change whether it is universal, big-endian universal, xor universal, delta universal, or strongly universal.

**Comment by lemire** [comment]
@jbapple 

That's not bad.

I understand what big-endian universality is... but what is the motivation? A shift is typically more expensive than a mask... so why would you want to extract the most significant bits instead of the least significant bits?

**Comment by jbapple** [comment]
Assume we have hashed the input down to 64 bits already, using whatever method one has for hashing long strings.

The fastest hash function I know for achieving almost delta universality on 64-bit inputs `(x*r128) >> 64`, where the multiplication is over 128 bits. Since you only have to compute 64 bits of the result, you can do this with two 64-bit multiplications, one addition, and no shifts. I don't know if this is [almost] xor universal; do you?

The fastest hash function I know for achieving almost big-endian universailty is multiplication by a single 64-bit random odd number, `(x*rOdd64)`.

On Haswell, according to Agner Fog's instruction tables, the reciprocal throughputs of the operations in questions are:

| Operation | Reciprocal throughput |
| --- | --- |
| Multiplication | 1 |
| Addition | 0.25 |
| Mask | 0.25 |
| Shift | 0.5 |

(assuming all operands are in registers already)

The motivation for iteratedCL was more about using less randomness (5 64-bit words). The cost, of course, is the numerator of the collision probability, which is about L/4 times higher than CLHASH.

**Comment by lemire** [comment]
@jbapple 

> Assume we have hashed the input down to 64 bits already, using whatever method one has for hashing long strings. (...) The fastest hash function I know for achieving almost delta universality on 64-bit inputs...

Are you saying that it is cheaper for you to produce a big-endian universal function than a delta universal function?

Fine if that is what you are saying. But if I am Joe the user. I take your hash values. I want a 16-bit hash value out of it. I am going to want to do `h(x) & 0xFFFF` and not `h(x) >> 16`. 

What am I missing?

> The motivation for iteratedCL was more about using less randomness (5 64-bit words). The cost, of course, is the numerator of the collision probability, which is about L/4 times higher than CLHASH.

That's a good motivation in itself, of course.

**Comment by jbapple** [comment]
> Are you saying that it is cheaper for you to produce a big-endian universal function than a delta universal function?

Yes.

> What am I missing [about Joe the user]?

Nothing! :-)

**Comment by lemire** [comment]
@jbapple 

Thanks. 

I am getting the following warnings with GCC 4.8 :

```
src/variablelengthbenchmark.c:86:49: warning: initialization from incompatible pointer type [enabled by default]
                                                 ,&twiceHorner32
                                                 ^
src/variablelengthbenchmark.c:86:49: warning: (near initialization for 'funcArr64[6]') [enabled by default]
src/variablelengthbenchmark.c:87:50: warning: initialization from incompatible pointer type [enabled by default]
                                                  ,&iterateCL11


src/benchmark.c:97:49: warning: initialization from incompatible pointer type [enabled by default]
                                                 &unrolledHorner4,
                                                 ^
src/benchmark.c:97:49: warning: (near initialization for 'funcArr64[8]') [enabled by default]
src/benchmark.c:99:49: warning: initialization from incompatible pointer type [enabled by default]
                                                 ,&iterateCL11
```

I am not concerned about the code being incorrect, but could you have a look at possibly silencing these warnings by making sure that the signatures match perfectly as far as the compiler is concerned?

**Comment by lemire** [comment]
@jbapple 

On my tests, I am getting that `iterateCL 11` is really very fast on long strings.

```
Google's City                        CPU cycle/byte = 0.239016   billions of bytes per second =  14.191671
64-bit VHASH                         CPU cycle/byte = 0.264845   billions of bytes per second =  12.808005
64-bit CLHASH                        CPU cycle/byte = 0.168924   billions of bytes per second =  20.080400
GFMultilinear                        CPU cycle/byte = 0.252544   billions of bytes per second =  13.431710
GFMultilinear (half multiplication)  CPU cycle/byte = 0.137871   billions of bytes per second =  24.603556
SipHash                              CPU cycle/byte = 2.123376   billions of bytes per second =  1.597523
GHASH                                CPU cycle/byte = 0.782145   billions of bytes per second =  4.336962
hornerHash                           CPU cycle/byte = 0.628952   billions of bytes per second =  5.393306
unrolled Horner                      CPU cycle/byte = 0.273234   billions of bytes per second =  12.414755
twice Horner32                       CPU cycle/byte = 0.255650   billions of bytes per second =  13.268546
iterateCL 11                         CPU cycle/byte = 0.145353   billions of bytes per second =  23.337702
```

The performance is less impressive on short strings however... but still good... (see below for some numbers)

Assuming that you do have the universality you claim, then it is quite impressive. I'd say it is remarkable.

When you write "approximately (L/2)/2^64 almost big-endian universal". What do you mean by "approximately"? Do you mean "given some reasonable effort, one could arrive at the exact bound". Or do you mean "I am guessing that it might have this bound, but it might take 30 MIT PhDs 30 years to determine whether my claim is true"? Or do you mean "I am guessing that while it might not have this property, but some small changes should be sufficient to give it the desired property". 

```
$ ./variablelengthbenchmark
#Reporting the number of cycles per byte.
#First number is input length in  8-byte words.
#          64-bit VHASH         64-bit CLHASH        Google's City        SipHash              GHASH           hornerHash           unrolled Horner      twice Horner32       iterateCL 11
       1         21.000000  16.500000  17.000000  24.000000  18.000000  14.000000  17.000000  14.000000  21.500000
       2         10.500000  8.250000  8.500000  13.000000  9.000000  7.250000  8.500000  7.250000  10.750000
       3         7.333333  5.666667  5.833333  9.500000  7.333333  5.166667  5.666667  5.333333  7.166667
       4         5.500000  4.375000  4.375000  7.625000  5.625000  4.000000  4.250000  4.125000  5.375000
       5         4.400000  3.500000  3.800000  6.500000  5.300000  3.300000  3.700000  3.300000  4.300000
       6         3.666667  3.000000  3.166667  5.750000  4.500000  2.750000  3.083333  2.833333  3.583333
       7         3.214286  2.571429  2.714286  5.214286  4.428571  2.428571  2.642857  2.428571  3.071429
       8         2.812500  2.250000  2.375000  4.875000  3.875000  2.187500  2.250000  2.187500  2.687500
       9         2.555556  2.055556  2.555556  4.555556  3.833333  2.055556  2.166667  1.944444  2.388889
      10         2.300000  1.900000  2.300000  4.300000  3.400000  1.900000  1.950000  1.800000  2.150000
      11         2.090909  1.727273  2.090909  4.090909  3.454545  1.772727  1.818182  1.636364  1.954545
      12         1.916667  1.541667  1.916667  3.916667  3.208333  1.666667  1.583333  1.541667  1.791667
      13         1.846154  1.461538  1.807692  3.769231  3.269231  1.576923  1.576923  1.423077  1.653846
      14         1.714286  1.357143  1.642857  3.642857  3.035714  1.500000  1.464286  1.357143  1.571429
      15         1.633333  1.266667  1.566667  3.566667  3.100000  1.466667  1.366667  1.266667  1.466667
      16         1.437500  1.156250  1.437500  3.468750  2.937500  1.406250  1.250000  1.218750  1.375000
      17         1.500000  1.147059  1.470588  3.382353  3.000000  1.382353  1.264706  1.176471  1.294118
      18         1.416667  1.083333  1.388889  3.305556  2.194444  1.333333  1.194444  1.111111  1.222222
      19         1.368421  1.026316  1.315789  3.236842  2.289474  1.289474  1.157895  1.052632  1.131579
      20         1.300000  0.950000  1.250000  3.175000  2.175000  1.250000  1.075000  1.025000  1.100000
      21         1.238095  0.928571  1.190476  3.119048  2.285714  1.238095  1.071429  0.976190  1.047619
      22         1.181818  0.909091  1.136364  3.068182  2.204545  1.204545  1.045455  0.954545  0.977273
      23         1.152174  0.869565  1.086957  3.043478  2.239130  1.173913  1.000000  0.913043  0.956522
      24         1.104167  0.854167  1.041667  3.000000  2.187500  1.145833  0.916667  0.875000  0.958333
      25         1.080000  0.800000  1.060000  2.940000  2.260000  1.140000  0.940000  0.860000  0.900000
      26         1.038462  0.788462  1.038462  2.923077  1.750000  1.115385  0.923077  0.826923  0.884615
      27         1.018519  0.777778  1.000000  2.907407  1.833333  1.092593  0.888889  0.814815  0.851852
      28         0.982143  0.732143  0.964286  2.857143  1.767857  1.071429  0.839286  0.803571  0.839286
      29         0.965517  0.724138  0.931034  2.827586  1.827586  1.068966  0.862069  0.775862  0.793103
      30         0.916667  0.700000  0.883333  2.800000  1.800000  1.050000  0.833333  0.750000  0.800000
      31         0.903226  0.693548  0.870968  2.790323  1.870968  1.032258  0.806452  0.725806  0.758065
      32         0.906250  0.656250  0.843750  2.765625  1.828125  1.015625  0.765625  0.718750  0.734375
      33         0.939394  0.651515  0.863636  2.742424  1.878788  1.015152  0.787879  0.696970  0.727273
      34         0.911765  0.632353  0.823529  2.735294  1.514706  1.000000  0.764706  0.691176  0.720588
      35         0.900000  0.628571  0.814286  2.700000  1.571429  0.985714  0.742857  0.671429  0.685714
      36         0.875000  0.597222  0.791667  2.694444  1.555556  0.972222  0.708333  0.666667  0.680556
      37         0.864865  0.581081  0.770270  2.675676  1.594595  0.972973  0.729730  0.662162  0.662162
      38         0.842105  0.565789  0.750000  2.671053  1.578947  0.960526  0.710526  0.644737  0.657895
      39         0.833333  0.564103  0.730769  2.653846  1.641026  0.948718  0.692308  0.628205  0.641026
      40         0.800000  0.550000  0.712500  2.625000  1.600000  0.937500  0.662500  0.612500  0.625000
      41         0.792683  0.548780  0.743902  2.609756  1.670732  0.939024  0.682927  0.609756  0.609756
      42         0.773810  0.535714  0.726190  2.595238  1.357143  0.928571  0.666667  0.607143  0.607143
      43         0.767442  0.534884  0.697674  2.593023  1.418605  0.918605  0.651163  0.593023  0.604651
      44         0.750000  0.511364  0.681818  2.579545  1.397727  0.920455  0.636364  0.579545  0.568182
      45         0.744444  0.511111  0.677778  2.577778  1.444444  0.911111  0.644444  0.577778  0.555556
      46         0.728261  0.500000  0.652174  2.554348  1.434783  0.902174  0.630435  0.576087  0.554348
      47         0.723404  0.500000  0.648936  2.553191  1.468085  0.893617  0.617021  0.563830  0.542553
      48         0.677083  0.479167  0.635417  2.562500  1.437500  0.895833  0.604167  0.552083  0.541667
      49         0.714286  0.469388  0.653061  2.551020  1.510204  0.887755  0.612245  0.551020  0.530612
      50         0.700000  0.470000  0.640000  2.540000  1.250000  0.880000  0.610000  0.550000  0.520000
      51         0.696078  0.460784  0.627451  2.529412  1.313725  0.872549  0.588235  0.539216  0.509804
      52         0.682692  0.442308  0.615385  2.528846  1.298077  0.875000  0.576923  0.528846  0.509615
      53         0.669811  0.443396  0.603774  2.509434  1.349057  0.867925  0.584906  0.528302  0.500000
      54         0.657407  0.435185  0.592593  2.509259  1.333333  0.861111  0.583333  0.527778  0.490741
      55         0.663636  0.436364  0.581818  2.500000  1.381818  0.854545  0.572727  0.518182  0.490909
      56         0.642857  0.437500  0.571429  2.482143  1.357143  0.857143  0.553571  0.508929  0.482143
      57         0.640351  0.429825  0.587719  2.473684  1.403509  0.850877  0.561404  0.508772  0.482456
      58         0.629310  0.431034  0.577586  2.474138  1.181034  0.844828  0.560345  0.508621  0.474138
      59         0.627119  0.423729  0.567797  2.466102  1.228814  0.838983  0.550847  0.500000  0.466102
      60         0.616667  0.416667  0.566667  2.458333  1.216667  0.841667  0.533333  0.491667  0.466667
      61         0.606557  0.409836  0.549180  2.459016  1.262295  0.836066  0.540984  0.491803  0.459016
      62         0.596774  0.403226  0.540323  2.443548  1.241935  0.830645  0.540323  0.491935  0.451613
      63         0.603175  0.396825  0.531746  2.444444  1.293651  0.825397  0.531746  0.484127  0.444444
      64         0.570312  0.390625  0.523438  2.429688  1.273438  0.828125  0.515625  0.476562  0.445312
```

**Comment by jbapple** [comment]
I sent a PR for the type match issue. I'm working on a proof of almost universality; I'll keep you updated with how it goes.

**Pull request merged**
