### PR TITLE
Generic treehash

### PR DESCRIPTION
**Pull request by jbapple**
Add generic treehash - generic over hashing algos.

This includes the fastest Sandy Bridge and Skylake hash functions (over long strings) that I have seen yet. These are not rigorously checked for correctness yet, but they are incremental changes to other, simpler, treehashes.

### CODE REVIEW

**Comment by lemire** [comment]
Numbers I get on Skylake processor...

```
$ ./variablelengthbenchmark
#Reporting the number of bytes per cycle.
#First number is input length in  8-byte words.
0 "&hashVHASH64" "&CLHASH" "&hashCity" "&hashSipHash" "&GHASH64bit" "(&generic_treehash<BoostedZeroCopyGenericBinaryTreehash, Wide<CLNH, 7> >)" "(&generic_treehash<BoostedZeroCopyGenericBinaryTreehash, Wide<NH, 9> >)"
(...)
  64         1.88  2.88  1.95  0.43  0.95  2.39  1.94
```

**Comment by jbapple** [comment]
I found graphing the whole output (ala fig 1(a) from the 2015 paper) interesting. Treehash performance is sawtooth-like, but surpasses CLHASH in speed at somewhere between a few hundred and a few thousand elements.

I think the intra-run variability comes from the "rollup" function. I think the inter-run variability comes from the instruction cache.

**Comment by lemire** [comment]
> I think the intra-run variability comes from the "rollup" function. I think the inter-run variability comes from the instruction cache.

Can you elaborate?

**Comment by jbapple** [comment]
Well, "rollup" behaves very differently when there are a lot of half-full levels in "workspace". In particular, it needs extra time because it calls T::Hash more often.

And when selecting a different set of functions to test, the icache faces different pressures. More (and longer) functions lead to more cache pressure.

I'm not sure that these explain the performance variability. I haven't even measured the inter-run variance.

**Pull request merged**
