### PR TITLE
Cl treehash

### PR DESCRIPTION
**Pull request by jbapple**

### CODE REVIEW

**Comment by lemire** [comment]
Looks like clang on travis does not like the new code, so disabling clang for now in https://github.com/lemire/StronglyUniversalStringHashing/commit/9d2646eb9eb56f41f05f7e0100b0ca62a8a6b758

**Comment by lemire** [comment]
Right. So the results are very good.

How many random bits do the tree hashing techniques require, compared with CLHash?

**Comment by jbapple** [comment]
The exact number of random bits required depends on the primitive used, but it takes O(log2 n) words of randomness to hash n words down to 1. Here, the constant is relatively small, like 2.

For example, using CLNH's delta-universality, the hash family defined by h_{a,b}(p,q,r) = (p + a)(q + b) + r is universal, where a, b, p, and q are polynomials of degree less than 64 over the field with two elements and r is a polynomial of degree less than 128 over the field with two elements. This family uses 128 random bits to hash 256 input bits down to 128 output bits.

Tree hashing with this primitive uses 128 \* ceiling(log2 n) bits to hash n 128-bit words down to one 128-bit word. Hashing the resulting output word down to 64 bits and then hashing in the string length costs a few more random bits - 3 more 128-bit words. The total is 6 + 2 ceiling(log2 n) 64-bit words, vs. CLHash's 133 words (ignoring for the moment strings shorter than 128 64-bit words).

**Comment by lemire** [comment]
Right. So while a bit slower, they use fewer random bits for the same type of universality. Of course, we could try to tune CLHash so that it uses fewer random bits too, and then see how the speed fares.

**Pull request merged**
